"""Automatic PR generator from GitHub Issues powered by Gemini 3.6."""

from __future__ import annotations

import json
import os
import subprocess
import sys
from google import genai

import memory


def run_cmd(cmd: list[str]) -> str:
    res = subprocess.run(cmd, capture_output=True, text=True)
    if res.returncode != 0:
        # Surface the command's stderr instead of swallowing it: a bare
        # CalledProcessError hides why (e.g. git rejecting a workflow-file push).
        sys.stderr.write(res.stderr)
        raise subprocess.CalledProcessError(res.returncode, cmd, res.stdout, res.stderr)
    return res.stdout.strip()


def is_workflow_path(path: str) -> bool:
    """True for files under .github/workflows/, which the Actions GITHUB_TOKEN
    is forbidden from pushing (needs a PAT with the 'workflow' scope)."""
    norm = os.path.normpath(path).replace(os.sep, "/").lstrip("/")
    return norm.startswith(".github/workflows/")


def comment_on_issue(issue_number: str, body: str) -> None:
    subprocess.run(
        ["gh", "issue", "comment", issue_number, "--body", body],
        capture_output=True,
        text=True,
    )


def main() -> int:
    issue_number = os.environ.get("ISSUE_NUMBER")
    issue_title = os.environ.get("ISSUE_TITLE", "")
    issue_body = os.environ.get("ISSUE_BODY", "")

    if not issue_number:
        print("Error: ISSUE_NUMBER environment variable is required", file=sys.stderr)
        return 1

    print(f"🚀 Processing Issue #{issue_number}: {issue_title}")

    client = genai.Client()
    model_name = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")

    system_instruction = (
        "You are an expert AI software engineer. Given an issue title and description, "
        "analyze the task and generate the precise file changes needed to satisfy the issue. "
        "You MUST respond with a single JSON object containing:\n"
        "- 'pr_title': string (short conventional commit style PR title)\n"
        "- 'pr_description': string (clear explanation of changes made, ending with 'Fixes #<issue_number>')\n"
        "- 'file_changes': array of objects with 'path' (relative file path) and 'content' (full complete file contents)"
    )

    mem = memory.render_memory(memory.load_memory("."), "issue")
    if mem:
        system_instruction += "\n\n" + mem

    prompt = f"""
Issue #{issue_number}: {issue_title}

Issue Description:
{issue_body}

Please generate the file changes to solve this issue.
"""

    print(f"🤖 Generating solution using model '{model_name}' …")
    response = client.models.generate_content(
        model=model_name,
        contents=prompt,
        config={
            "system_instruction": system_instruction,
            "response_mime_type": "application/json",
        },
    )

    raw_text = response.text or "{}"
    if raw_text.startswith("```"):
        raw_text = raw_text.split("\n", 1)[-1].rsplit("```", 1)[0].strip()

    try:
        data = json.loads(raw_text)
    except json.JSONDecodeError as e:
        print(f"❌ Failed to parse JSON response from Gemini: {e}\nRaw output:\n{raw_text}", file=sys.stderr)
        return 1

    pr_title = data.get("pr_title", f"fix: resolve Issue #{issue_number} - {issue_title}")
    pr_body = data.get("pr_description", f"Automated PR generated for Issue #{issue_number}.\n\nFixes #{issue_number}")
    if f"#{issue_number}" not in pr_body:
        pr_body += f"\n\nFixes #{issue_number}"

    file_changes = data.get("file_changes", [])
    if not file_changes:
        print("⚠️ No file changes generated by the model.")
        return 0

    # The Actions GITHUB_TOKEN cannot push to .github/workflows/, and letting an
    # AI auto-commit runnable CI (which runs with the repo's secrets) is a real
    # security risk. Skip any workflow files the model proposes.
    skipped = [c["path"] for c in file_changes if is_workflow_path(c.get("path", ""))]
    file_changes = [c for c in file_changes if not is_workflow_path(c.get("path", ""))]
    for path in skipped:
        print(
            f"⛔ Skipping workflow file '{path}': the Actions GITHUB_TOKEN cannot "
            f"push to .github/workflows/. Add it manually or via a PAT with the "
            f"'workflow' scope."
        )

    if not file_changes:
        note = (
            f"🤖 I generated changes for this issue, but they only touched "
            f"GitHub Actions workflow files ({', '.join(skipped)}), which this "
            f"bot cannot push (the Actions token lacks the `workflow` scope). "
            f"No PR was opened — please add these manually or provide a PAT with "
            f"the `workflow` scope."
        )
        print(f"⚠️ {note}")
        comment_on_issue(issue_number, note)
        return 0

    if skipped:
        pr_body += (
            f"\n\n> ⚠️ Note: skipped workflow file(s) {', '.join(skipped)} — the "
            f"Actions token cannot push to `.github/workflows/`. Add them "
            f"manually or via a PAT with the `workflow` scope."
        )

    branch_name = f"auto-fix/issue-{issue_number}"

    print(f"🌿 Setting up branch '{branch_name}' and applying changes …")
    run_cmd(["git", "config", "user.name", "github-actions[bot]"])
    run_cmd(["git", "config", "user.email", "github-actions[bot]@users.noreply.github.com"])
    run_cmd(["git", "checkout", "-b", branch_name])

    for change in file_changes:
        path = change["path"]
        content = change["content"]
        parent_dir = os.path.dirname(path)
        if parent_dir:
            os.makedirs(parent_dir, exist_ok=True)
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        run_cmd(["git", "add", path])
        print(f"  ✓ Updated/Created: {path}")

    commit_msg = f"fix: resolve Issue #{issue_number}\n\n{issue_title}"
    run_cmd(["git", "commit", "-m", commit_msg])

    print(f"⬆️ Pushing branch '{branch_name}' to GitHub …")
    run_cmd(["git", "push", "-u", "origin", branch_name, "--force"])

    print("📬 Opening Pull Request …")
    res = subprocess.run(
        [
            "gh", "pr", "create",
            "--title", pr_title,
            "--body", pr_body,
            "--base", "main",
            "--head", branch_name,
        ],
        capture_output=True,
        text=True,
    )

    if res.returncode == 0:
        print(f"🎉 Pull Request created successfully!\n{res.stdout.strip()}")
    else:
        print(f"⚠️ PR creation note: {res.stderr.strip() or res.stdout.strip()}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
